<?php
/** @var \Codilar\BuyerGst\Block\Order\Comment $block */
?>
<?php if($comment = $block->getBuyerGst()):?>
<div class="block block-order-details-view">
    <div class="block-content">
        <div class="box box-purchase-purpose">
            <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Buyer GST') ?></span></strong>
            <div class="box-content">
               <?php echo $block->getBuyerGstHtml();?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>